In [2]:
import numpy as np

In [3]:
type(np.array([1,2,3,])) ## converting list into array

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [31]:
type(np.array([1,2,3], ndmin=3))

numpy.ndarray

In [8]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
x=np.array(([(1,2),(3,4)]), dtype=[('a','<f2'),('b','<i4')])

In [25]:
x[1][0]

3.0

In [21]:
type(x[0][0])

numpy.float16

In [27]:
a=np.mat('1 2;3 4')
type(a)

numpy.matrix

In [28]:
a


matrix([[1, 2],
        [3, 4]])

In [30]:
a=[1,2]
np.asarray(a)

array([1, 2])

In [32]:
np.asanyarray(a)

array([1, 2])

In [37]:
a=[1,2,3]
b=np.asanyarray(a)

In [38]:
np.asanyarray(b)

array([1, 2, 3])

In [40]:
a= np.matrix([1,2])
np.asanyarray(a)

matrix([[1, 2]])

In [43]:
x=np.array([1,2,3])
y=x


In [46]:
y[0]=10
y


array([10,  2,  3])

In [47]:
x ## solo copy changes made at one place reflected at other places 

array([10,  2,  3])

In [48]:
z=np.copy(x)

In [49]:
z

array([10,  2,  3])

In [50]:
z[0]=5

In [51]:
x

array([10,  2,  3])

In [52]:
z ### deep copy 

array([5, 2, 3])

In [2]:
 np.fromfunction(lambda i,j:i == j , (3,3), dtype = int) ## fromfunction takes other function to generate array based on somke certain condition 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
np.fromfunction(lambda i,j:i+j , (3,3), dtype = int) 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [4]:
 np.fromfunction(lambda i,j,k:i*j *k, (3,3,3), dtype = int) ## 3d array using fromfunction

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [5]:
iterable= (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000147B2622448>

In [6]:
np.fromiter(iterable,float) ## iterator conversion to array 

array([ 0.,  1.,  4.,  9., 16.])

In [7]:
np.fromstring('1,2' , dtype=int, sep=',') ## coverting string into array()

array([1, 2])

In [15]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [20]:
r=np.core.records.fromarrays([x1,x2,x3,x4])## data according to the indexes odd diff dataframes
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [19]:
type(r)

numpy.recarray

In [26]:
r[1]['f0']

2

In [27]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))

Type/Class of this object: <class 'numpy.ndarray'>


In [30]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print(mat) ##dimension
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [31]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [35]:
## range fuction does not work for float 
np.arange(5,10,.8) ## for float this works 

array([5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [36]:
np.arange(5.2,10,.8)

array([5.2, 6. , 6.8, 7.6, 8.4, 9.2])

In [37]:
np.linspace(1,5,50) ## generates ; start,end,number of data

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [38]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [39]:
np.linspace(10,50,5 , endpoint=False)

array([10., 18., 26., 34., 42.])

In [40]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [51]:
np.ones((3,4,2))## 3 arrays of 4x2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [3]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.eye(4) ## identity matrix with n=4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.linspace(2,3,num=5,retstep=True) ## give the step size between the two datas

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [6]:
np.logspace(2,3,num=5 , base=10)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [16]:
5*2 +np.zeros((3,4,8))

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [2]:
import numpy as np
np.arange(4,80,8)

array([ 4, 12, 20, 28, 36, 44, 52, 60, 68, 76])

In [9]:
k=np.ones((4,5,2))
k

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
k.ndim ## dimension

3

In [10]:
k.size

40

In [11]:
k.shape

(4, 5, 2)

In [13]:
k.dtype

dtype('float64')

In [15]:
x1=np.zeros((3,3,3))
x2=np.ones((3,3,3))
x1 + x2 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])