In [2]:
import numpy as np 

In [5]:
np.arange(16).shape

(16,)

In [4]:
np.arange(16).reshape(-1,4) ## reshaping array into a matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.arange(16).reshape(2,8) 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [7]:
np.arange(16).reshape(8,2)  

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [8]:
np.arange(16).reshape(1,-1)   ## 1x whatever size of the dataset, negative number should be in any one dimension only 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [26]:
x=np.arange(16).reshape(-1,4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
np.diag(x,k=1) ## after leaving first row and column it will give diagonal of remaining square matrix

array([ 1,  6, 11])

In [22]:
np.diag(x,k=2) 

array([2, 7])

In [27]:
np.diag(x,k=-1) ## oppsite side diagonal given 

array([ 4,  9, 14])

In [28]:
np.diag(x,k=-2) ## oppsite side diagonal given 

array([ 8, 13])

In [29]:
np.diag(np.diag(x,k=-2) ) ## construct square matrix using previously found diagonal element 

array([[ 8,  0],
       [ 0, 13]])

In [23]:
np.diag(x,k=3) 

array([3])

In [14]:
np.diag(x)

array([ 0,  5, 10, 15])

In [24]:
x=np.arange(16).reshape(-1,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [25]:
np.diag(x) ##diagonal element of first square matrix , if not in nxn format 

array([0, 9])

In [30]:
## diagflat 
np.diagflat([[1,2],[3,4]])## list inside list and reconstruct square matrix with values alog diagonal 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
np.diagflat([[1,2],[3,4]], k=1) ## same concept of  K

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [34]:
##tri function 
np.tri(3,3,0,dtype=int)## lower traingle =1 

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [35]:
np.tri(3,3,1,dtype=int) ## here k=1 , same concept as previous 

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
np.tri(5,5,2,dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.tri(5,7,1,dtype=int) # remove first row and columns and then try to create a square matrix then apply 

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0]])

In [41]:
##tril
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0) ## triangle lower, data avaialble above will be deactivated

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [42]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1) 

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
##triu
np.triu([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [45]:
# Random number generation
print(np.random.rand(2,3))## smaple from uniform distribution

[[0.46991917 0.23097467 0.23194813]
 [0.53272208 0.99674235 0.69799526]]


In [46]:
print(np.random.randn(2,3)) ## smaple from standarad normal distribution mu=0, std deviation = 1

[[-1.06020602 -0.74073983 -1.88216558]
 [ 0.33414994 -1.41980742  0.27870194]]


In [55]:
print(np.random.randint(1,10,))

1


In [67]:
print(np.random.randint(1,10,(4,4)))

[[8 4 2 3]
 [7 3 6 6]
 [9 5 8 6]
 [7 8 6 9]]


In [68]:
from numpy.random import randint as ri 

In [71]:
a=ri(1,200,10)
np.sort(a)

array([ 14,  15,  45,  45,  49,  55,  59,  93, 117, 127])

In [72]:
b=ri(1,100,25).reshape(5,5)
b

array([[ 5, 55, 49, 57,  1],
       [77, 34, 82, 74, 40],
       [27, 36,  7, 33, 68],
       [64, 66, 28, 81, 52],
       [60, 52, 83, 67, 55]])

In [75]:
q=np.sort(b, axis=1) ## while sorting the data has mpved along the column only
q

array([[ 1,  5, 49, 55, 57],
       [34, 40, 74, 77, 82],
       [ 7, 27, 33, 36, 68],
       [28, 52, 64, 66, 81],
       [52, 55, 60, 67, 83]])

In [76]:
q.max()

83

In [77]:
q.min()

1

In [80]:
q.argmax(axis =1) # return column  indices of the maimum values along the given axis 

array([4, 4, 4, 4, 4], dtype=int64)

In [81]:
q.argmax(axis =0) #return column  indices of the maimum values along t

array([4, 4, 1, 1, 4], dtype=int64)

In [83]:
q.argmax() # return index of max data in frame

24

In [ ]:
## argmax flattens data set in a row and then returns index of max 

In [84]:
x=np.arange(0,11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [86]:
x[3:6:2] # start end step size 

array([3, 5])

In [89]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
mat > 50

array([[False,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [ True, False,  True,  True, False]])

In [91]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
mat2

array([[4, 9, 8],
       [8, 7, 8],
       [4, 1, 5]])

In [92]:
mat1

array([[5, 7, 7],
       [9, 3, 9],
       [2, 3, 2]])

In [93]:
mat1*mat2 ## index wise  multiplication 

array([[20, 63, 56],
       [72, 21, 72],
       [ 8,  3, 10]])

In [94]:
mat1@mat2 ## matrix multiplication

array([[104, 101, 131],
       [ 96, 111, 141],
       [ 40,  41,  50]])

In [95]:
mat1**3

array([[125, 343, 343],
       [729,  27, 729],
       [  8,  27,   8]], dtype=int32)

In [97]:
pow(mat1,3)

array([[125, 343, 343],
       [729,  27, 729],
       [  8,  27,   8]], dtype=int32)

In [99]:
## Broadcasting 
start = np.zeros((4,4))
start = start + 100 ## element wise broadcasting 
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [100]:
add_rows = np.array([1, 0 ,2,5])

In [101]:
print(add_rows)

[1 0 2 5]


In [103]:
y = add_rows + start
y ### row wise broadcasting 

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [109]:
add_cols=np.array([[0,1,2,3]]).T

In [110]:
add_cols + start

array([[100., 100., 100., 100.],
       [101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.]])