In [12]:
import pandas as pd
import numpy as np

In [61]:
a=pd.read_csv('ex5.csv')
a

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [9]:
a.dtypes


something     object
a              int64
b              int64
c            float64
d              int64
message       object
dtype: object

In [15]:
b=a.dtypes[a.dtypes =="int64"].index

In [16]:
a[b].describe()

a     b     d
count  3.0   3.0   3.0
mean   5.0   6.0   8.0
std    4.0   4.0   4.0
min    1.0   2.0   4.0
25%    3.0   4.0   6.0
50%    5.0   6.0   8.0
75%    7.0   8.0  10.0
max    9.0  10.0  12.0

In [18]:
k=a['a']

In [23]:
a['b'] 

0     2
1     6
2    10
Name: b, dtype: int64

In [25]:
j=a['b'][::2] ## diplaying data at even positions
j

0     2
2    10
Name: b, dtype: int64

In [24]:
type(a['b'][::2])

pandas.core.series.Series

In [32]:
df=pd.DataFrame(j)
df

b
0   2
2  10

In [29]:
type(df)

pandas.core.frame.DataFrame

In [36]:
l=df.sort_values(by='b')
l

b
0   2
2  10

In [3]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [42]:
type(titanic_train["Pclass"])

pandas.core.series.Series

In [53]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [44]:
titanic_train['Cabin']


0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ... 
151      C2
152     NaN
153     NaN
154     NaN
155     NaN
Name: Cabin, Length: 156, dtype: object

In [45]:
type(titanic_train['Cabin'])

pandas.core.series.Series

In [54]:
[Cabin[0] for Cabin in char_Cabin]

list

In [57]:
##new columns and insert first letter from each record of cabin in this new columns
char_Cabin = titanic_train["Cabin"].astype(str)
new_Cabin = [Cabin[0] for Cabin in char_Cabin] ## extracting first letter from each row 
new_Cabin=pd.Categorical(new_Cabin)
titanic_train['new_Cabin']=new_Cabin

In [7]:
titanic_train['Age'].isnull() == 'True'

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154    False
155    False
Name: Age, Length: 156, dtype: bool

In [11]:
##extract indexes from data where null value
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [66]:
titanic_train['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [16]:
row_index=np.where(titanic_train["Fare"]== max(titanic_train["Fare"]))

In [17]:
##selectin row (loc,iloc,ix)
titanic_train.iloc[row_index]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare        Cabin Embarked  
27  19.0      3      2  19950  263.0  C23 C25 C27        S  
88  23.0      3      2  19950  263.0  C23 C25 C27        S

In [20]:
titanic_train.iloc[row_index][['Name','Age']]

Name   Age
27  Fortune, Mr. Charles Alexander  19.0
88      Fortune, Miss. Mabel Helen  23.0

In [24]:
k=np.where(titanic_train['Age']==min(titanic_train['Age']))
titanic_train.iloc[k][['Name','Age','Cabin']]

Name   Age Cabin
78  Caldwell, Master. Alden Gates  0.83   NaN

In [26]:
## concat two clumn and create third column
titanic_train['Family'] = titanic_train['SibSp'] + titanic_train['Parch']

0      1
1      1
2      0
3      1
4      0
      ..
151    1
152    0
153    2
154    0
155    1
Name: Family, Length: 156, dtype: int64

In [34]:
most_family=np.where(titanic_train["Family"]==max(titanic_train["Family"]))
most_family

(array([59, 71], dtype=int64),)

In [35]:
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  Family  
59  11.0      5      2  CA 2144  46.9   NaN        S       7  
71  16.0      5      2  CA 2144  46.9   NaN        S       7

In [36]:
labels = ['a','b','c']
my_data = [10,20,30]
arr=np.array(my_data)
d = {'a':10, 'b':20, 'c':30}
print("Labels :", labels)
print("My data :", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels) ## coverting the data into series

Labels : ['a', 'b', 'c']
My data : [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [38]:
t=pd.Series(my_data, index=labels)
t[2]

30

In [44]:
d={'a':"asdf",'b':20, 'c':30}
##pd.DataFrame(d) #can not do ,,ike this need to give index
pd.DataFrame(d , index=['s','k','m']) ## need to give index

a   b   c
s  asdf  20  30
k  asdf  20  30
m  asdf  20  30

In [46]:
pd.Series([type, sum, max]) ## pasing inbuilt functions

0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object

In [51]:
ser1 = pd.Series([1,2,3,4], ['CA','OR', 'CO','CA'])
ser2 = pd.Series([1,2,5,4], ['CA', 'NV','AZ','OR'])
ser3 =ser1+ser2 ## Same will happen in multiplication
ser3 

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [51]:
from numpy.random import randn as rn
#np.random.seed(101) # seed generate same kind of random data, 
                    #same random seed then random data generated will be same 
matrix_data=rn(5,4)
matrix_data


array([[-1.18648376, -0.28928992, -0.29993101, -0.47550662],
       [-0.41857084, -2.58642582,  1.99197552, -0.32216102],
       [ 0.14404376,  1.17350349, -0.03573242,  0.28362463],
       [ 0.26001216, -0.93104149, -0.59701672, -0.58806587],
       [-0.13823115, -0.87096111, -1.21601033,  0.40658225]])

In [69]:
row_labels = [12,33,34,45,56]
column_headings = ['W','X','Y','Z']



In [61]:
df =pd.DataFrame(matrix_data)
df

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [70]:
df1 =pd.DataFrame(matrix_data,row_labels,column_headings)
df1

W         X         Y         Z
12  2.706850  0.628133  0.907969  0.503826
33  0.651118 -0.319318 -0.848077  0.605965
34 -2.018168  0.740122  0.528813 -0.589001
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [63]:
 ## extracting data from df1 
df1['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [64]:
## Extract Row 
df1.loc['E'] ## understands named indexes not default ones 


W    0.190794
X    1.978757
Y    2.605967
Z    0.683509
Name: E, dtype: float64

In [68]:
df1.iloc[4] ## takes integer location "default" indexes : 0,1,2,3.4...

W    0.190794
X    1.978757
Y    2.605967
Z    0.683509
Name: E, dtype: float64

In [71]:
df1

W         X         Y         Z
12  2.706850  0.628133  0.907969  0.503826
33  0.651118 -0.319318 -0.848077  0.605965
34 -2.018168  0.740122  0.528813 -0.589001
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [73]:
df1.iloc[[3,4]] ## extracting 2 rows 

W         X         Y         Z
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [74]:
df1.iloc[[3,4],[2]] ##first list is row , 2 list is column

Y
45 -0.933237
56  2.605967

In [75]:
df1.iloc[[1,2],[1,2]]

X         Y
33 -0.319318 -0.848077
34  0.740122  0.528813

In [77]:
df1

W         X         Y         Z
12  2.706850  0.628133  0.907969  0.503826
33  0.651118 -0.319318 -0.848077  0.605965
34 -2.018168  0.740122  0.528813 -0.589001
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [78]:
df1.iloc[[0,4],[0,3]]

W         Z
12  2.706850  0.503826
56  0.190794  0.683509

In [81]:
df1.loc[33:45,'W':'Y'] ## using in form of a range

W         X         Y
33  0.651118 -0.319318 -0.848077
34 -2.018168  0.740122  0.528813
45  0.188695 -0.758872 -0.933237

In [83]:
## dropping a column /row
df1.drop('X', axis=1) # 0 means row , 1 means column


W         Y         Z
12  2.706850  0.907969  0.503826
33  0.651118 -0.848077  0.605965
34 -2.018168  0.528813 -0.589001
45  0.188695 -0.933237  0.955057
56  0.190794  2.605967  0.683509

In [84]:
df1 ## not dropped permanently  x column, "inplace" param if false changes not poermanent 


W         X         Y         Z
12  2.706850  0.628133  0.907969  0.503826
33  0.651118 -0.319318 -0.848077  0.605965
34 -2.018168  0.740122  0.528813 -0.589001
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [87]:
df1.drop(34, axis=0, inplace=True) ## understands only named indexes 

In [88]:
df1

W         X         Y         Z
12  2.706850  0.628133  0.907969  0.503826
33  0.651118 -0.319318 -0.848077  0.605965
45  0.188695 -0.758872 -0.933237  0.955057
56  0.190794  1.978757  2.605967  0.683509

In [90]:
print(df1>0)

       W      X      Y     Z
12  True   True   True  True
33  True  False  False  True
45  True  False  False  True
56  True   True   True  True


In [103]:
df1[df1.loc[[12]] > 0] ### conditional filtering operation 

W         X         Y         Z
12  2.70685  0.628133  0.907969  0.503826
33      NaN       NaN       NaN       NaN
45      NaN       NaN       NaN       NaN
56      NaN       NaN       NaN       NaN

In [7]:
matrix_data=np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [46]:
row_labels=['A','B','C','D','E']
column_headings = ['Age', 'Height','Weight']
df= pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [18]:
df.loc[['A','B'],['Height','Weight']]

Height  Weight
A      66     140
B      70     148

In [16]:
df['Age']

A    22
B    42
C    30
D    35
E    25
Name: Age, dtype: int32

In [20]:
df['Height'] <65

A    False
B    False
C     True
D    False
E     True
Name: Height, dtype: bool

In [19]:
df[df['Height'] <65] ## height less than 65

Age  Height  Weight
C   30      62     125
E   25      62     152

In [28]:
df

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [27]:
df[(df['Age'] == 30) & (df['Height'] ==62) & (df['Weight'] ==125)]

Age  Height  Weight
C   30      62     125

In [29]:
df.reset_index()

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [36]:
df.drop('Age', axis=1)

Height  Weight
A      66     140
B      70     148
C      62     125
D      68     160
E      62     152

In [38]:
df.reset_index()

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [47]:
df.reset_index(drop=True , inplace=True) ## prev indexes removed 
df

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [49]:
## split()
df['Random']="Lovish Pandey Python Code vsd".split()
df

Age  Height  Weight  Random
0   22      66     140  Lovish
1   42      70     148  Pandey
2   30      62     125  Python
3   35      68     160    Code
4   25      62     152     vsd

In [50]:
df.set_index('Age') ## sets the named colums as index

Height  Weight  Random
Age                        
22       66     140  Lovish
42       70     148  Pandey
30       62     125  Python
35       68     160    Code
25       62     152     vsd

In [78]:
## multi herarchy index 
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))

In [79]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print(hier_index)
type(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


pandas.core.indexes.multi.MultiIndex

In [80]:
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)

        A    B    C
G1 1 -1.0  1.0  0.0
   2 -1.0 -1.0 -0.0
   3 -1.0  1.0 -1.0
G2 1 -1.0  0.0 -1.0
   2 -1.0  0.0  1.0
   3  2.0  0.0 -1.0


In [82]:
df1.loc['G1']

A    B    C
1 -1.0  1.0  0.0
2 -1.0 -1.0 -0.0
3 -1.0  1.0 -1.0

In [88]:
df1.loc['G1'].loc[[2,3],['B','C']] ## extracting data through myulti heirarchy table

B    C
2 -1.0 -0.0
3  1.0 -1.0

In [94]:
l1=['A','A','A','B','B','B','C','C','C']
l2=[1,2,3,1,2,3,1,2,3]
l3=[1,2,3,4,5,6,7,8,9]
k=index = list(zip(l1,l2,l3))
k

[('A', 1, 1),
 ('A', 2, 2),
 ('A', 3, 3),
 ('B', 1, 4),
 ('B', 2, 5),
 ('B', 3, 6),
 ('C', 1, 7),
 ('C', 2, 8),
 ('C', 3, 9)]

In [96]:
index = pd.MultiIndex.from_tuples(index)
print(index)

MultiIndex([('A', 1, 1),
            ('A', 2, 2),
            ('A', 3, 3),
            ('B', 1, 4),
            ('B', 2, 5),
            ('B', 3, 6),
            ('C', 1, 7),
            ('C', 2, 8),
            ('C', 3, 9)],
           )


In [97]:
df1 = pd.DataFrame(data=np.round(rn(9,4)), index= index, columns= ['A','B','C','D'])
print(df1)

         A    B    C    D
A 1 1 -1.0  0.0  1.0 -1.0
  2 2  0.0  1.0  1.0  0.0
  3 3  1.0 -0.0 -2.0 -2.0
B 1 4 -0.0 -1.0 -0.0 -0.0
  2 5  2.0  2.0  1.0 -0.0
  3 6  0.0 -0.0  1.0 -2.0
C 1 7 -0.0  0.0  0.0 -1.0
  2 8  1.0 -0.0 -1.0  1.0
  3 9 -0.0 -1.0  2.0  1.0


In [101]:
df1.loc ['A'].iloc[[0,1],[1,3]]

B    D
1 1  0.0 -1.0
2 2  1.0  0.0